### ISSUE TITLE
autos bijhouden

### ISSUE THREAD

**Issue by njittam** [RSDT/JH-API#3]
zie RSDT/Japp#75

**Comment by Area348** [comment]
Zie API handleiding

**Comment by njittam** [comment]
//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /car/ was not found on this server.</p>\n<hr>\n<address>Apache/2.4.9 (Win64) PHP/5.5.12 Server at jotihunt-api-v3.area348.nl Port 80</address>\n</body></html>\n'

**Comment by Area348** [comment]
Is in middels al gefixed, was mijn fout... iets met /car moet /auto zijn...
MyBad
