### ISSUE TITLE
aankunnen geven of er al een tegenhunt is geweest op een blokhut.

### ISSUE THREAD

**Issue by njittam** [RSDT/JH-API#4]
zie RSDT/Japp#75

**Comment by Area348** [comment]
@njittam:  Hoe had je dit in gedachten?

Tegenhunt / true/false? en auto reset na 00:00u?

**Comment by njittam** [comment]
Ik heb er even over nagedacht. En ik denk dat een timestamp met de laatste Tegenhunt handiger is. 

Daarnaast is het ook misschien handig om een bron veld aan te maken. Het komt wel is voor dat andere hunters denken/zeggen dat een HB al een Tegenhunt heeft gehad terwijl die er nog niet is geweest.

**Comment by Area348** [comment]
Date stamp van de huidige tegenhunt dag aangemaakt.

**Tegenhunt;Verkrijg de laatste tegenhunt dag.**
_API:  V3.0
HTTP METHOD: GET
URL: /tegenhunt/SLEUTEL/last
CONTENT: -
RESPONSE:
{
"date":		"<DATE>"
}
INFO:	
	De datum van de tegenhunt kan via de website (moderators) aangepast worden.
Wat hij doet is dat hij gewoon dan de huidige dag -1 dag doet in de db._	



Ik zie echter niet in waarom je een tegenhunt van een andere groep zou willen op slaan of niet.

1. Niet ons probleem.
2. Wij moeten het ook van geruchten hebben dus het blijft een denken/zeggen
3. Je kunt het zelf wel na gaan of ze ergens geweest zijn aan de gelopen route.
