### ISSUE TITLE
getAutoInfoByGebruikersId

### ISSUE THREAD

**Issue by njittam** [RSDT/JH-API#5]
kan er een getAutoInfoByGebruikersId komen?

Dat het zelfde doet als auto/{sleutel}/info/{id}

**Comment by Area348** [comment]
Geloof dat ik je weer eens niet kan volgend.
Wat jij op vraagt doet dat al precies....

Of bedoe je toevallig dit:
URL: /auto/SLEUTEL/onecar/naam
(Alle inzittende)

**Comment by Area348** [comment]
**Aangemaakt:**

Car; Krijg alle inzittende van 1 auto by eigenaarID
Dit hoeft dus niet de eigenaar van de auto te zijn.

API:  V3.0
HTTP METHOD: GET
URL: /auto/SLEUTEL/onecar/ID
CONTENT: -
RESPONSE:
[
{
"id":			"<ID>",
"datetime":		"<datetime>",
"gebruikersNaam":	"<naam>",
"gebruikerID":		"<id>",
"autoEigenaar":	"<naam>",	
"rol":			"<rol>"
}
,
{	
"id":			"<ID>",
"datetime":		"<datetime>",
"gebruikersNaam":	"<naam>",
"gebruikerID":		"<id>",
"autoEigenaar":	"<naam>",	
"rol":			"<rol>"
}
,
{		
"id":			"<ID>",
"datetime":		"<datetime>",
"gebruikersNaam":	"<naam>",
"gebruikerID":		"<id>",
"autoEigenaar":	"<naam>",	
"rol":			"<rol>"
}
]

**Comment by Area348** [comment]
Done
